# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./customtimectrl.h \
    ./customtimectrlplugin.h
SOURCES += ./customtimectrl.cpp \
    ./customtimectrlplugin.cpp
FORMS += ./datetime.ui
RESOURCES += ./customtimectrl.qrc
