# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./catchinputctrl.h \
    ./catchinputctrlplugin.h
SOURCES += ./catchinputctrl.cpp \
    ./catchinputctrlplugin.cpp
FORMS += ./catchinputfrm.ui
RESOURCES += ./CatchInputCtrl.qrc
